import type { Product } from "@/types/product";
import { CATALOG_2026_PRODUCTS } from "./catalog-2026";

export const SITE_NAME = "Mioralane";
export const SITE_DESCRIPTION =
  "Authentic Korean skincare delivered to Bangladesh. COSRX, Beauty of Joseon, ANUA, Purito — batch-verified, beautifully packaged.";
export const SITE_URL = "https://mioralane.com";

// WhatsApp order number (international format, digits only — replace with the real number)
export const SITE_WHATSAPP = "8801700000000";

export const ANNOUNCEMENT_TEXT =
  "Free delivery on orders over ৳2,000 in Dhaka · Cash on Delivery available";

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/shop" },
  { label: "Combo", href: "/combo" },
  { label: "Offers", href: "/shop?sort=offers" },
  { label: "New Arrival", href: "/shop?sort=newest" },
  { label: "Best Seller", href: "/shop?sort=best-seller" },
];

export const BRANDS = [
  "3W Clinic",
  "AESTURA",
  "APLB",
  "APRILSKIN",
  "Abib",
  "Acwell",
  "Anua",
  "Aromatica",
  "Axis-Y",
  "BAREN",
  "BELIF",
  "BEPLAIN",
  "BIODANCE",
  "Banila CO",
  "Beauty of Joseon",
  "Benton",
  "Bonajour",
  "COSRX",
  "Celimax",
  "I'm From",
  "Illiyoon",
  "JIGOTT",
  "Mediheal",
  "Mise en Scene",
  "Nature Republic",
  "NEOGEN",
  "Numbuzin",
  "Purito",
  "Round Lab",
  "SKIN1004",
  "Some By Mi",
  "Torriden",
  "VT Cosmetics",
];

export const CATEGORIES = [
  { id: "1", name: "Cleansers", slug: "cleansers", productCount: 12 },
  { id: "2", name: "Serums", slug: "serums", productCount: 18 },
  { id: "3", name: "Moisturizers", slug: "moisturizers", productCount: 15 },
  { id: "4", name: "Masks", slug: "masks", productCount: 8 },
  { id: "5", name: "Sun Care", slug: "sun-care", productCount: 6 },
  { id: "6", name: "Sets", slug: "sets", productCount: 4 },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "cosrx-snail",
    slug: "advanced-snail-96-mucin-power-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    description:
      "96% snail secretion filtrate deeply hydrates and repairs damaged skin. A cult favorite that works exceptionally well in humid climates.",
    longDescription:
      "96% snail secretion filtrate deeply hydrates and repairs damaged skin. A cult favorite that works exceptionally well in humid climates — lightweight, non-greasy, and absorbs in seconds.",
    price: 2250,
    krw: "₩26,000",
    images: ["/images/cosrx-snail.jpg"],
    category: "serums",
    brand: "COSRX",
    tags: ["hydration", "repair"],
    concerns: ["Hydration", "Repair"],
    tag: "best",
    rating: 4.8,
    reviewCount: 124,
    stock: 50,
    skinType: "All skin types",
    volume: "100ml",
    size: "100ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 450, stock: 20 },
      { label: "30ml", volume: "30ml", price: 950, stock: 30 },
      { label: "100ml", volume: "100ml", price: 2250, stock: 50 },
      {
        label: "100ml+ (Value)",
        volume: "100ml",
        price: 2100,
        compareAtPrice: 2250,
        stock: 15,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "CSRX-SNAIL-100",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-01-15",
  },
  {
    id: "anua-oil",
    slug: "heartleaf-pore-control-cleansing-oil",
    name: "Heartleaf Pore Control Cleansing Oil",
    description:
      "Gentle cleansing oil with heartleaf extract that dissolves makeup and sunscreen without stripping.",
    price: 1850,
    krw: "₩22,000",
    images: ["/images/anua-oil.jpg"],
    category: "cleansers",
    brand: "ANUA",
    tags: ["pores", "sensitive"],
    concerns: ["Pores", "Sensitive"],
    tag: "best",
    rating: 4.7,
    reviewCount: 98,
    stock: 35,
    skinType: "All skin types",
    volume: "200ml",
    size: "200ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 350, stock: 25 },
      { label: "30ml", volume: "30ml", price: 550, stock: 30 },
      { label: "200ml", volume: "200ml", price: 1850, stock: 35 },
      {
        label: "200ml+ (Value)",
        volume: "200ml",
        price: 1700,
        compareAtPrice: 1850,
        stock: 15,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "ANUA-OIL-200",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-02-20",
  },
  {
    id: "beauty-of-joseon-sun",
    slug: "relief-sun-rice-probiotics-spf50",
    name: "Relief Sun Rice + Probiotics SPF50+",
    description:
      "Rice bran and probiotic-derived ingredients protect skin from UV while brightening. Lightweight, no white cast.",
    price: 1650,
    krw: "₩19,800",
    images: ["/images/beauty-of-joseon-sun.jpg"],
    category: "sun-care",
    brand: "Beauty of Joseon",
    tags: ["uv-protection", "brightening"],
    concerns: ["UV Protection", "Brightening"],
    tag: "best",
    rating: 4.9,
    reviewCount: 203,
    stock: 60,
    skinType: "All skin types",
    volume: "50ml",
    size: "50ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 450, stock: 30 },
      { label: "30ml", volume: "30ml", price: 1100, stock: 40 },
      { label: "50ml", volume: "50ml", price: 1650, stock: 60 },
      {
        label: "50ml+ (Value)",
        volume: "50ml",
        price: 1500,
        compareAtPrice: 1650,
        stock: 20,
      },
    ],
    source: "Stylevana, Seoul",
    sku: "BOJ-SUN-50",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-03-05",
  },
  {
    id: "purito-bamboo",
    slug: "bamboo-cream-panthenol-5",
    name: "Bamboo Cream Panthenol 5%",
    description:
      "Soothing bamboo water and panthenol cream that strengthens the skin barrier. Fragrance-free.",
    price: 1950,
    krw: "₩23,000",
    images: ["/images/purito-bamboo.jpg"],
    category: "moisturizers",
    brand: "Purito",
    tags: ["moisture", "sensitive"],
    concerns: ["Moisture", "Sensitive"],
    tag: null,
    rating: 4.6,
    reviewCount: 67,
    stock: 25,
    skinType: "Sensitive / Dry",
    volume: "50ml",
    size: "50ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 450, stock: 20 },
      { label: "30ml", volume: "30ml", price: 1100, stock: 25 },
      { label: "50ml", volume: "50ml", price: 1950, stock: 25 },
      {
        label: "50ml+ (Value)",
        volume: "50ml",
        price: 1800,
        compareAtPrice: 1950,
        stock: 10,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "PURITO-BAMBOO-50",
    isNew: false,
    isBestSeller: false,
    createdAt: "2024-04-12",
  },
  {
    id: "skin1004-probio",
    slug: "probio-cica-ampoule",
    name: "Probio-Cica Ampoule",
    description:
      "Fermented centella asiatica and probiotic complex that calms, repairs, and firms.",
    price: 2100,
    krw: "₩25,000",
    images: ["/images/skin1004-probio.jpg"],
    category: "serums",
    brand: "SKIN1004",
    tags: ["anti-aging", "repair"],
    concerns: ["Anti-aging", "Repair"],
    tag: "new",
    rating: 4.7,
    reviewCount: 45,
    stock: 30,
    skinType: "Mature / Dry",
    volume: "50ml",
    size: "50ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 500, stock: 15 },
      { label: "30ml", volume: "30ml", price: 1300, stock: 25 },
      { label: "50ml", volume: "50ml", price: 2100, stock: 30 },
      {
        label: "50ml+ (Value)",
        volume: "50ml",
        price: 1950,
        compareAtPrice: 2100,
        stock: 10,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "SKIN1004-PROBIO-50",
    isNew: true,
    isBestSeller: false,
    createdAt: "2024-05-10",
  },
  {
    id: "beauty-of-joseon-glow",
    slug: "glow-serum-propolis-niacinamide",
    name: "Glow Serum Propolis + Niacinamide",
    description:
      "Propolis extract and 2% niacinamide work together to brighten dull skin and control excess oil.",
    price: 1500,
    krw: "₩18,000",
    images: ["/images/beauty-of-joseon-glow.jpg"],
    category: "serums",
    brand: "Beauty of Joseon",
    tags: ["brightening", "acne"],
    concerns: ["Brightening", "Acne"],
    tag: null,
    rating: 4.8,
    reviewCount: 156,
    stock: 45,
    skinType: "Oily / Combination",
    volume: "30ml",
    size: "30ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 550, stock: 20 },
      { label: "30ml", volume: "30ml", price: 1500, stock: 45 },
      { label: "50ml", volume: "50ml", price: 2200, stock: 20 },
      {
        label: "30ml+ (Value)",
        volume: "30ml",
        price: 1350,
        compareAtPrice: 1500,
        stock: 15,
      },
    ],
    source: "Stylevana, Seoul",
    sku: "BOJ-GLOW-30",
    isNew: false,
    isBestSeller: false,
    createdAt: "2024-03-20",
  },
  {
    id: "cosrx-low-ph",
    slug: "low-ph-good-morning-gel-cleanser",
    name: "Low pH Good Morning Gel Cleanser",
    description:
      "Tea tree oil and BHA in a low-pH formula that cleanses without disrupting your skin barrier.",
    price: 1100,
    krw: "₩13,000",
    images: ["/images/cosrx-low-ph.jpg"],
    category: "cleansers",
    brand: "COSRX",
    tags: ["acne", "sensitive"],
    concerns: ["Acne", "Sensitive"],
    tag: null,
    rating: 4.6,
    reviewCount: 89,
    stock: 55,
    skinType: "Oily / Acne-prone",
    volume: "150ml",
    size: "150ml",
    sizeOptions: [
      { label: "10ml Mini", volume: "10ml", price: 250, stock: 30 },
      { label: "30ml", volume: "30ml", price: 400, stock: 35 },
      { label: "150ml", volume: "150ml", price: 1100, stock: 55 },
      {
        label: "150ml+ (Value)",
        volume: "150ml",
        price: 1000,
        compareAtPrice: 1100,
        stock: 20,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "CSRX-LOWPH-150",
    isNew: false,
    isBestSeller: false,
    createdAt: "2024-02-10",
  },
  {
    id: "skin1004-mini",
    slug: "madagascar-centella-travel-kit",
    name: "Madagascar Centella Travel Kit",
    description:
      "Four travel-sized centella products — toner, ampoule, cream, and sun serum.",
    price: 950,
    krw: "₩12,000",
    images: ["/images/skin1004-mini.jpg"],
    category: "sets",
    brand: "SKIN1004",
    tags: ["sensitive", "hydration"],
    concerns: ["Sensitive", "Hydration"],
    tag: "new",
    rating: 4.5,
    reviewCount: 32,
    stock: 40,
    skinType: "All skin types",
    volume: "4 × 20ml",
    size: "4 × 20ml",
    sizeOptions: [
      { label: "4 × 20ml Kit", volume: "4 × 20ml", price: 950, stock: 40 },
    ],
    source: "Olive Young, Seoul",
    sku: "SKIN1004-MINI-KIT",
    isNew: true,
    isBestSeller: false,
    createdAt: "2024-06-01",
  },
  // Combo / Bundle products
  {
    id: "combo-glass-skin",
    slug: "glass-skin-4-step-routine",
    name: "Glass Skin 4-Step Routine",
    description:
      "The complete Korean glass skin routine in one bundle: Cleanser + Toner + Serum + Moisturizer + Sunscreen. Save 15% compared to buying individually.",
    price: 4250,
    krw: "₩52,000",
    images: ["/images/promo-routine.jpg"],
    category: "combo",
    brand: "Mioralane Bundle",
    tags: ["complete-routine", "best-value"],
    concerns: ["Complete Routine", "Best Value"],
    tag: "best",
    rating: 4.9,
    reviewCount: 89,
    stock: 20,
    skinType: "All skin types",
    volume: "5-piece set",
    size: "5-piece set",
    sizeOptions: [
      { label: "5-Piece Set", volume: "5-piece set", price: 4250, stock: 20 },
    ],
    source: "Curated by Mioralane",
    sku: "MIOR-COMBO-GLASS",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-01-01",
  },
  {
    id: "combo-travel-kit",
    slug: "travel-essentials-kit",
    name: "Travel Essentials Kit",
    description:
      "Mini versions of our bestsellers — perfect for travel or trying before committing to full sizes.",
    price: 1850,
    krw: "₩22,000",
    images: ["/images/promo-minis.jpg"],
    category: "combo",
    brand: "Mioralane Bundle",
    tags: ["travel-size", "try-before-buy"],
    concerns: ["Travel Size", "Try Before Buy"],
    tag: "new",
    rating: 4.7,
    reviewCount: 45,
    stock: 30,
    skinType: "All skin types",
    volume: "4-piece mini set",
    size: "4-piece mini set",
    sizeOptions: [
      {
        label: "4-Piece Mini Set",
        volume: "4-piece mini set",
        price: 1850,
        stock: 30,
      },
    ],
    source: "Curated by Mioralane",
    sku: "MIOR-COMBO-TRAVEL",
    isNew: true,
    isBestSeller: false,
    createdAt: "2024-06-15",
  },
  {
    id: "combo-acne-set",
    slug: "acne-fighter-bundle",
    name: "Acne Fighter Bundle",
    description:
      "Target acne with COSRX Low pH Cleanser + COSRX Snail Mucin + Beauty of Joseon Glow Serum. A powerful 3-step routine for breakout-prone skin.",
    price: 3200,
    krw: "₩40,000",
    images: ["/images/cosrx-snail.jpg"],
    category: "combo",
    brand: "Mioralane Bundle",
    tags: ["acne", "oil-control"],
    concerns: ["Acne", "Oil Control"],
    tag: "best",
    rating: 4.8,
    reviewCount: 67,
    stock: 25,
    skinType: "Oily / Acne-prone",
    volume: "3-piece set",
    size: "3-piece set",
    sizeOptions: [
      { label: "3-Piece Set", volume: "3-piece set", price: 3200, stock: 25 },
    ],
    source: "Curated by Mioralane",
    sku: "MIOR-COMBO-ACNE",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-03-01",
  },
  // Discounted products for Offers
  {
    id: "offer-serum",
    slug: "heartleaf-77-soothing-toner",
    name: "Heartleaf 77% Soothing Toner",
    description:
      "77% heartleaf extract toner that soothes redness and hydrates deeply. A gentle formula perfect for sensitive skin in humid climates.",
    price: 1290,
    compareAtPrice: 1650,
    krw: "₩18,000",
    images: ["/images/anua-oil.jpg"],
    category: "toners",
    brand: "ANUA",
    tags: ["soothing", "hydration"],
    concerns: ["Soothing", "Hydration"],
    tag: "best",
    rating: 4.8,
    reviewCount: 156,
    stock: 40,
    skinType: "All skin types",
    volume: "250ml",
    size: "250ml",
    sizeOptions: [
      { label: "30ml", volume: "30ml", price: 350, stock: 20 },
      { label: "100ml", volume: "100ml", price: 750, stock: 30 },
      {
        label: "250ml",
        volume: "250ml",
        price: 1290,
        compareAtPrice: 1650,
        stock: 40,
      },
      {
        label: "250ml+ (Value)",
        volume: "250ml",
        price: 1150,
        compareAtPrice: 1650,
        stock: 15,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "ANUA-TONER-250",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-04-20",
  },
  {
    id: "offer-cream",
    slug: "ceramide-ato-concentrate-cream",
    name: "Ceramide Ato Concentrate Cream",
    description:
      "Rich ceramide cream that repairs and strengthens the skin barrier. Fragrance-free and ideal for post-procedure care.",
    price: 1650,
    compareAtPrice: 2100,
    krw: "₩22,000",
    images: ["/images/purito-bamboo.jpg"],
    category: "moisturizers",
    brand: "Illiyoon",
    tags: ["barrier-repair", "moisture"],
    concerns: ["Barrier Repair", "Moisture"],
    tag: "best",
    rating: 4.7,
    reviewCount: 98,
    stock: 35,
    skinType: "Dry / Sensitive",
    volume: "200ml",
    size: "200ml",
    sizeOptions: [
      { label: "30ml", volume: "30ml", price: 550, stock: 20 },
      { label: "100ml", volume: "100ml", price: 1050, stock: 30 },
      {
        label: "200ml",
        volume: "200ml",
        price: 1650,
        compareAtPrice: 2100,
        stock: 35,
      },
      {
        label: "200ml+ (Value)",
        volume: "200ml",
        price: 1500,
        compareAtPrice: 2100,
        stock: 15,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "ILLIYOON-CERAMIDE-200",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-05-05",
  },
  {
    id: "offer-mask",
    slug: "nmf-aquaring-ampoule-mask",
    name: "N.M.F Aquaring Ampoule Mask",
    description:
      "Intensive hydration sheet mask with hyaluronic acid and aloe vera. Perfect for a quick moisture boost in dry air-conditioned environments.",
    price: 750,
    compareAtPrice: 1100,
    krw: "₩12,000",
    images: ["/images/skin1004-mini.jpg"],
    category: "masks",
    brand: "Mediheal",
    tags: ["hydration", "quick-fix"],
    concerns: ["Hydration", "Quick Fix"],
    tag: "new",
    rating: 4.6,
    reviewCount: 203,
    stock: 60,
    skinType: "All skin types",
    volume: "10 sheets",
    size: "10 sheets",
    sizeOptions: [
      { label: "1 Sheet", volume: "1 sheet", price: 90, stock: 100 },
      { label: "5 Sheets", volume: "5 sheets", price: 400, stock: 50 },
      {
        label: "10 Sheets",
        volume: "10 sheets",
        price: 750,
        compareAtPrice: 1100,
        stock: 60,
      },
      {
        label: "10 Sheets (Value)",
        volume: "10 sheets",
        price: 680,
        compareAtPrice: 1100,
        stock: 30,
      },
    ],
    source: "Olive Young, Seoul",
    sku: "MEDIHEAL-NMF-10",
    isNew: true,
    isBestSeller: false,
    createdAt: "2024-06-10",
  },
  ...CATALOG_2026_PRODUCTS,
];

export const SKIN_TYPES = [
  { label: "All Skin Types", value: "all" },
  { label: "Dry", value: "dry" },
  { label: "Oily", value: "oily" },
  { label: "Combination", value: "combination" },
  { label: "Sensitive", value: "sensitive" },
  { label: "Normal", value: "normal" },
];

export const SORT_OPTIONS = [
  { label: "Newest", value: "newest" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Top Rated", value: "popularity" },
];
