export const SITE_NAME = "Mioralane";
export const SITE_DESCRIPTION =
  "Authentic Korean skincare delivered to Bangladesh. COSRX, Beauty of Joseon, ANUA, Purito — batch-verified, beautifully packaged.";
export const SITE_URL = "https://mioralane.com";

export const ANNOUNCEMENT_TEXT =
  "Free delivery on orders over ৳2,000 in Dhaka · Cash on Delivery available";

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/shop" },
  { label: "Combo", href: "/shop?category=combo" },
  { label: "Offers", href: "/shop?sort=offers" },
  { label: "New Arrival", href: "/shop?sort=newest" },
  { label: "Best Seller", href: "/shop?sort=best-seller" },
];

export const BRANDS = [
  "3W Clinic",
  "AESTURA",
  "APLB",
  "APRILSKIN",
  "Abib",
  "Acwell",
  "Anua",
  "Aromatica",
  "Axis-Y",
  "BAREN",
  "BELIF",
  "BEPLAIN",
  "BIODANCE",
  "Banila CO",
  "Beauty of Joseon",
  "Benton",
  "Bonajour",
  "COSRX",
  "Celimax",
  "I'm From",
  "Illiyoon",
  "JIGOTT",
  "Mediheal",
  "Mise en Scene",
  "Nature Republic",
  "NEOGEN",
  "Numbuzin",
  "Purito",
  "Round Lab",
  "SKIN1004",
  "Some By Mi",
  "Torriden",
  "VT Cosmetics",
];

export const CATEGORIES = [
  { id: "1", name: "Cleansers", slug: "cleansers", productCount: 12 },
  { id: "2", name: "Serums", slug: "serums", productCount: 18 },
  { id: "3", name: "Moisturizers", slug: "moisturizers", productCount: 15 },
  { id: "4", name: "Masks", slug: "masks", productCount: 8 },
  { id: "5", name: "Sun Care", slug: "sun-care", productCount: 6 },
  { id: "6", name: "Sets", slug: "sets", productCount: 4 },
];

export const DUMMY_PRODUCTS = [
  {
    id: "1",
    slug: "advanced-snail-96-mucin-power-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    description:
      "96% snail secretion filtrate deeply hydrates and repairs damaged skin. A cult favorite that works exceptionally well in humid climates.",
    longDescription:
      "96% snail secretion filtrate deeply hydrates and repairs damaged skin. A cult favorite that works exceptionally well in humid climates — lightweight, non-greasy, and absorbs in seconds.",
    price: 2250,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop",
    ],
    category: "serums",
    brand: "COSRX",
    tags: ["hydration", "repair", "best"],
    rating: 4.8,
    reviewCount: 124,
    stock: 50,
    skinType: "All skin types",
    volume: "100ml",
    source: "Olive Young, Seoul",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    slug: "heartleaf-pore-control-cleansing-oil",
    name: "Heartleaf Pore Control Cleansing Oil",
    description:
      "Gentle cleansing oil with heartleaf extract that dissolves makeup and sunscreen without stripping.",
    price: 1850,
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop",
    ],
    category: "cleansers",
    brand: "ANUA",
    tags: ["pores", "sensitive", "best"],
    rating: 4.7,
    reviewCount: 98,
    stock: 35,
    skinType: "All skin types",
    volume: "200ml",
    source: "Olive Young, Seoul",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-02-20",
  },
  {
    id: "3",
    slug: "relief-sun-rice-probiotics-spf50",
    name: "Relief Sun Rice + Probiotics SPF50+",
    description:
      "Rice bran and probiotic-derived ingredients protect skin from UV while brightening. Lightweight, no white cast.",
    price: 1650,
    images: [
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop",
    ],
    category: "sun-care",
    brand: "Beauty of Joseon",
    tags: ["uv-protection", "brightening", "best"],
    rating: 4.9,
    reviewCount: 203,
    stock: 60,
    skinType: "All skin types",
    volume: "50ml",
    source: "Stylevana, Seoul",
    isNew: false,
    isBestSeller: true,
    createdAt: "2024-03-05",
  },
  {
    id: "4",
    slug: "bamboo-cream-panthenol-5",
    name: "Bamboo Cream Panthenol 5%",
    description:
      "Soothing bamboo water and panthenol cream that strengthens the skin barrier. Fragrance-free.",
    price: 1950,
    images: [
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&h=600&fit=crop",
    ],
    category: "moisturizers",
    brand: "Purito",
    tags: ["moisture", "sensitive"],
    rating: 4.6,
    reviewCount: 67,
    stock: 25,
    skinType: "Sensitive / Dry",
    volume: "50ml",
    source: "Olive Young, Seoul",
    isNew: false,
    isBestSeller: false,
    createdAt: "2024-04-12",
  },
  {
    id: "5",
    slug: "probio-cica-ampoule",
    name: "Probio-Cica Ampoule",
    description:
      "Fermented centella asiatica and probiotic complex that calms, repairs, and firms.",
    price: 2100,
    images: [
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&h=600&fit=crop",
    ],
    category: "serums",
    brand: "SKIN1004",
    tags: ["anti-aging", "repair", "new"],
    rating: 4.7,
    reviewCount: 45,
    stock: 30,
    skinType: "Mature / Dry",
    volume: "50ml",
    source: "Olive Young, Seoul",
    isNew: true,
    isBestSeller: false,
    createdAt: "2024-05-10",
  },
  {
    id: "6",
    slug: "glow-serum-propolis-niacinamide",
    name: "Glow Serum Propolis + Niacinamide",
    description:
      "Propolis extract and 2% niacinamide work together to brighten dull skin and control excess oil.",
    price: 1500,
    images: [
      "https://images.unsplash.com/photo-1570194065650-d99fb4ee8e39?w=600&h=600&fit=crop",
    ],
    category: "serums",
    brand: "Beauty of Joseon",
    tags: ["brightening", "acne"],
    rating: 4.8,
    reviewCount: 156,
    stock: 45,
    skinType: "Oily / Combination",
    volume: "30ml",
    source: "Stylevana, Seoul",
    isNew: false,
    isBestSeller: false,
    createdAt: "2024-03-20",
  },
  {
    id: "7",
    slug: "low-ph-good-morning-gel-cleanser",
    name: "Low pH Good Morning Gel Cleanser",
    description:
      "Tea tree oil and BHA in a low-pH formula that cleanses without disrupting your skin barrier.",
    price: 1100,
    images: [
      "https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600&h=600&fit=crop",
    ],
    category: "cleansers",
    brand: "COSRX",
    tags: ["acne", "sensitive"],
    rating: 4.6,
    reviewCount: 89,
    stock: 55,
    skinType: "Oily / Acne-prone",
    volume: "150ml",
    source: "Olive Young, Seoul",
    isNew: false,
    isBestSeller: false,
    createdAt: "2024-02-10",
  },
  {
    id: "8",
    slug: "madagascar-centella-travel-kit",
    name: "Madagascar Centella Travel Kit",
    description:
      "Four travel-sized centella products — toner, ampoule, cream, and sun serum.",
    price: 950,
    images: [
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop",
    ],
    category: "sets",
    brand: "SKIN1004",
    tags: ["sensitive", "hydration", "new"],
    rating: 4.5,
    reviewCount: 32,
    stock: 40,
    skinType: "All skin types",
    volume: "4 × 20ml",
    source: "Olive Young, Seoul",
    isNew: true,
    isBestSeller: false,
    createdAt: "2024-06-01",
  },
];

export const SKIN_TYPES = [
  { label: "All Skin Types", value: "all" },
  { label: "Dry", value: "dry" },
  { label: "Oily", value: "oily" },
  { label: "Combination", value: "combination" },
  { label: "Sensitive", value: "sensitive" },
  { label: "Normal", value: "normal" },
];

export const SORT_OPTIONS = [
  { label: "Newest", value: "newest" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Top Rated", value: "rating" },
];
